### ISSUE TITLE
Cant link required libraries

### ISSUE THREAD

**Issue by emreeebozkurt** [futurepress/epubjs-rn#140]
Hi, i install epubjs-rn, when i link required libraries but when i run-android get this error;

```
Loading dependency graph...jest-haste-map: Haste module naming collision: react-native
  The following files share their name; please adjust your hasteImpl:
    * <rootDir>\node_modules\react-native\package.json
    * <rootDir>\node_modules\epubjs-rn\node_modules\react-native\package.json

Failed to construct transformer:  { Error: Duplicated files or mocks. Please check the console for more info
    at setModule (D:\reactn\testEpub\node_modules\jest-haste-map\build\index.js:620:17)
    at workerReply (D:\reactn\testEpub\node_modules\jest-haste-map\build\index.js:691:9)
    at process._tickCallback (internal/process/next_tick.js:68:7)
  mockPath1: 'node_modules\\react-native\\package.json',
  mockPath2:
   'node_modules\\epubjs-rn\\node_modules\\react-native\\package.json' }
(node:15228) UnhandledPromiseRejectionWarning: Error: Duplicated files or mocks. Please check the console for more info
    at setModule (D:\reactn\testEpub\node_modules\jest-haste-map\build\index.js:620:17)
    at workerReply (D:\reactn\testEpub\node_modules\jest-haste-map\build\index.js:691:9)
    at process._tickCallback (internal/process/next_tick.js:68:7)
(node:15228) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 1)
(node:15228) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.
```

**Comment by reyzaraf** [comment]
i have some problem with you sir , after install and link the library

**Comment by chiragbatra29** [comment]
![Screenshot_1567754375](https://user-images.githubusercontent.com/22887382/64408559-ae5c2880-d0a4-11e9-9a2f-20e4b24fbb01.png)

Going through the same problem with "react-native": "0.60.5"

**Comment by abdullatif422** [comment]
Did anyone fix this., ?

**Comment by medmo7** [comment]
Any fix? having the same problem after installing the library, just with the install not linked yet

**Comment by waredjal** [comment]
Got the same issue, still no fix @fchasen ?
Thanks guys for the great work
