### ISSUE TITLE
Unable to resolve module `fs`

### ISSUE THREAD

**Issue by 7daysofrain** [futurepress/epubjs-rn#34]
Hi,

I suddently started to see this error when i start the app. Don't know what exactly happened but i can make it work anymore. Here is the error and the package json. Can someone help me? Thanks

Error:

```
Loading dependency graph, done.
error: bundling: UnableToResolveError: Unable to resolve module `fs` from `/Volumes/DATOS/Proyectos/black-noir/client/BlackNoir/node_modules/epubjs-rn/src/Epub.js`: Module does not exist in the module map or in these directories:
  /Volumes/DATOS/Proyectos/black-noir/client/BlackNoir/node_modules/epubjs-rn/node_modules
,   /Volumes/DATOS/Proyectos/black-noir/client/BlackNoir/node_modules

This might be related to https://github.com/facebook/react-native/issues/4968
To resolve try the following:
  1. Clear watchman watches: `watchman watch-del-all`.
  2. Delete the `node_modules` folder: `rm -rf node_modules && npm install`.
  3. Reset packager cache: `rm -fr $TMPDIR/react-*` or `npm start -- --reset-cache`.
    at UnableToResolveError (/Volumes/DATOS/Proyectos/black-noir/client/BlackNoir/node_modules/react-native/packager/src/node-haste/DependencyGraph/ResolutionRequest.js:525:5)
    at ResolutionRequest._resolveNodeDependency (/Volumes/DATOS/Proyectos/black-noir/client/BlackNoir/node_modules/react-native/packager/src/node-haste/DependencyGraph/ResolutionRequest.js:394:11)
    at ResolutionRequest.resolveDependency (/Volumes/DATOS/Proyectos/black-noir/client/BlackNoir/node_modules/react-native/packager/src/node-haste/DependencyGraph/ResolutionRequest.js:141:29)
    at dependencyNames.map.name (/Volumes/DATOS/Proyectos/black-noir/client/BlackNoir/node_modules/react-native/packager/src/node-haste/DependencyGraph/ResolutionRequest.js:145:59)
    at Array.map (native)
    at ResolutionRequest.resolveModuleDependencies (/Volumes/DATOS/Proyectos/black-noir/client/BlackNoir/node_modules/react-native/packager/src/node-haste/DependencyGraph/ResolutionRequest.js:145:42)
    at module.read.then (/Volumes/DATOS/Proyectos/black-noir/client/BlackNoir/node_modules/react-native/packager/src/node-haste/DependencyGraph/ResolutionRequest.js:172:40)
    at process._tickCallback (internal/process/next_tick.js:103:7)
Bundling `index.ios.js`  99.7% (1299/1301), failed.
```
package.json

```
{
	"name": "BlackNoir",
	"version": "0.0.1",
	"private": true,
	"scripts": {
		"start": "node node_modules/react-native/local-cli/cli.js start",
		"lint": "standard --verbose | snazzy",
		"lintdiff": "git diff --name-only --cached --relative | grep '\\.js$' | xargs standard | snazzy",
		"fixcode": "standard --fix",
		"clean": "rm -rf $TMPDIR/react-* && watchman watch-del-all && npm cache clean",
		"clean:android": "cd android/ && ./gradlew clean && cd .. && react-native run-android",
		"newclear": "rm -rf $TMPDIR/react-* && watchman watch-del-all && rm -rf ios/build && rm -rf node_modules/ && npm cache clean && npm i",
		"test": "ava",
		"test:watch": "ava --watch",
		"coverage": "nyc ava && nyc report --reporter=html && open coverage/index.html || xdg-open coverage/index.html",
		"android:build": "cd android && ./gradlew assembleRelease",
		"android:install": "cd android && ./gradlew assembleRelease && ./gradlew installRelease",
		"android:hockeyapp": "cd android && ./gradlew assembleRelease && puck -submit=auto app/build/outputs/apk/app-release.apk",
		"android:devices": "$ANDROID_HOME/platform-tools/adb devices",
		"android:logcat": "$ANDROID_HOME/platform-tools/adb logcat *:S ReactNative:V ReactNativeJS:V",
		"android:shake": "$ANDROID_HOME/platform-tools/adb devices | grep '\\t' | awk '{print $1}' | sed 's/\\s//g' | xargs -I {} $ANDROID_HOME/platform-tools/adb -s {} shell input keyevent 82",
		"precommit": "npm run git-hook",
		"prepush": "npm run git-hook",
		"git-hook": "npm run lint -s && npm test -s"
	},
	"dependencies": {
		"apisauce": "^0.10.0",
		"epubjs": "^0.3.37",
		"epubjs-rn": "0.0.75",
		"format-json": "^1.0.3",
		"lodash": "^4.17.2",
		"querystringify": "0.0.4",
		"ramda": "^0.23.0",
		"react": "16.0.0-alpha.6",
		"react-native": "^0.44.3",
		"react-native-animatable": "^1.1.1",
		"react-native-check-box": "^1.0.4",
		"react-native-config": "^0.2.1",
		"react-native-device-info": "^0.10.0",
		"react-native-drawer": "^2.3.0",
		"react-native-fetch-blob": "0.10.5",
		"react-native-fs": "^2.3.2",
		"react-native-hyperlink": "0.0.9",
		"react-native-in-app-utils": "^5.2.3",
		"react-native-modal": "^2.4.0",
		"react-native-orientation": "git+https://github.com/yamill/react-native-orientation.git",
		"react-native-router-flux": "^3.37.0",
		"react-native-splash-screen": "^2.0.0",
		"react-native-static-server": "0.1.7",
		"react-native-visible-scrollview": "0.0.6",
		"react-native-zip-archive": "1.1.1",
		"react-navigation": "^1.0.0-beta.7",
		"react-redux": "^5.0.2",
		"redux": "^3.6.0",
		"redux-persist": "^4.1.0",
		"redux-saga": "^0.14.3",
		"redux-thunk": "^2.2.0",
		"reduxsauce": "0.4.1",
		"seamless-immutable": "^7.0.1"
	},
	"devDependencies": {
		"ava": "^0.18.2",
		"babel-eslint": "^7.1.1",
		"babel-plugin-module-resolver": "^2.5.0",
		"babel-plugin-static-fs": "^1.1.0",
		"babel-preset-es2015": "^6.18.0",
		"enzyme": "^2.6.0",
		"husky": "^0.13.1",
		"ignite-animatable": "^0.3.1",
		"ignite-dev-screens": "^2.0.0-beta.8",
		"ignite-ir-boilerplate-2016": "^0.2.1",
		"mockery": "^2.0.0",
		"nyc": "^10.1.2",
		"path": "^0.12.7",
		"react-addons-test-utils": "^15.3.1",
		"react-dom": "^15.4.0",
		"react-native-mock": "^0.3.1",
		"reactotron-apisauce": "^1.7.0",
		"reactotron-react-native": "^1.7.0",
		"reactotron-redux": "^1.7.0",
		"reactotron-redux-saga": "^1.7.0",
		"snazzy": "^6.0.0",
		"standard": "8.6.0"
	},
	"ava": {
		"files": [
			"Tests/**/*.js",
			"!Tests/Setup.js"
		],
		"require": [
			"babel-register",
			"babel-polyfill",
			"react-native-mock/mock",
			"./Tests/Setup"
		],
		"babel": "inherit"
	},
	"standard": {
		"parser": "babel-eslint",
		"globals": [
			"describe",
			"it",
			"fetch",
			"navigator",
			"__DEV__",
			"XMLHttpRequest",
			"FormData",
			"React$Element"
		]
	},
	"config": {
		"ghooks": {
			"pre-commit": "if [ -d 'ignite-base' ]; then cd ignite-base; fi; npm run lint"
		}
	},
	"rnpm": {
		"assets": [
			"./App/Themes/Fonts"
		]
	}
}
```

**Comment by 7daysofrain** [comment]
sorry, solved, my bad, i was importing the files directly from the src folder instead the library. Two days for that silly mistake :(
