### ISSUE TITLE
Upgrade epub.js to v0.4?

### ISSUE THREAD

**Issue by johanpoirier** [futurepress/epubjs-rn#88]
Hi,

Thanks for this project, it has been a great help for me.

I was wondering if upgrading epub.js to v0.4 has been considered yet?
I would be happy to help if necessary.

Thanks for the answer.

**Comment by johanpoirier** [comment]
I tried to use epub.js v.0.4.2 in epubjs-rn. I got this error:

```
Loading dependency graph, done.
error: bundling failed: Error: Unable to resolve module `./utils` from `/Users/someuser/workspace/someproject/node_modules/epubjs/dist/epub.js`: The module `./utils` could not be found from `/Users/someuser/workspace/someproject/node_modules/epubjs/dist/epub.js`. Indeed, none of these files exist:

  * `/Users/someuser/workspace/someproject/node_modules/epubjs/dist/utils(.native||.android.js|.native.js|.js|.android.json|.native.json|.json)`
  * `/Users/someuser/workspace/someproject/node_modules/epubjs/dist/utils/index(.native||.android.js|.native.js|.js|.android.json|.native.json|.json)`
    at ModuleResolver.resolveDependency (/Users/someuser/workspace/someproject/node_modules/metro/src/node-haste/DependencyGraph/ModuleResolution.js:161:851)
    at ResolutionRequest.resolveDependency (/Users/someuser/workspace/someproject/node_modules/metro/src/node-haste/DependencyGraph/ResolutionRequest.js:91:16)
    at DependencyGraph.resolveDependency (/Users/someuser/workspace/someproject/node_modules/metro/src/node-haste/DependencyGraph.js:272:4579)
    at dependencies.map.relativePath (/Users/someuser/workspace/someproject/node_modules/metro/src/DeltaBundler/traverseDependencies.js:376:19)
    at Array.map (<anonymous>)
    at resolveDependencies (/Users/someuser/workspace/someproject/node_modules/metro/src/DeltaBundler/traverseDependencies.js:374:16)
    at /Users/someuser/workspace/someproject/node_modules/metro/src/DeltaBundler/traverseDependencies.js:212:33
    at Generator.next (<anonymous>)
    at step (/Users/someuser/workspace/someproject/node_modules/metro/src/DeltaBundler/traverseDependencies.js:297:313)
    at /Users/someuser/workspace/someproject/node_modules/metro/src/DeltaBundler/traverseDependencies.js:297:473
 BUNDLE  [android, dev] ./index.js ▓▓▓▓▓▓▓▓▓▓░░░░░░ 62.8% (493/634), failed.
```

**Comment by hesampour** [comment]
when the v4 will be released?
